create table if not exists public.release_announcements (
    id bigint generated by default as identity primary key,
    app_name text not null default 'site',
    version text not null,
    summary text not null default '',
    announced_at timestamptz not null default timezone('utc'::text, now()),
    raw_payload jsonb not null default '{}'::jsonb
);

alter table public.release_announcements
    add column if not exists app_name text;

alter table public.release_announcements
    add column if not exists version text;

alter table public.release_announcements
    add column if not exists summary text;

alter table public.release_announcements
    add column if not exists announced_at timestamptz;

alter table public.release_announcements
    add column if not exists raw_payload jsonb;

update public.release_announcements
set app_name = 'site'
where app_name is null or btrim(app_name) = '';

update public.release_announcements
set summary = ''
where summary is null;

update public.release_announcements
set announced_at = timezone('utc'::text, now())
where announced_at is null;

update public.release_announcements
set raw_payload = '{}'::jsonb
where raw_payload is null;

alter table public.release_announcements
    alter column app_name set default 'site',
    alter column app_name set not null,
    alter column version set not null,
    alter column summary set default '',
    alter column summary set not null,
    alter column announced_at set default timezone('utc'::text, now()),
    alter column announced_at set not null,
    alter column raw_payload set default '{}'::jsonb,
    alter column raw_payload set not null;

alter table public.release_announcements
    drop constraint if exists release_announcements_version_key;

drop index if exists public.release_announcements_version_uidx;
drop index if exists public.release_announcements_version_key;

create unique index if not exists release_announcements_app_name_version_uidx
    on public.release_announcements (app_name, version);

create index if not exists release_announcements_announced_at_idx
    on public.release_announcements (announced_at desc);
