export type SkillKey =
    | "force"
    | "brace"
    | "feat"
    | "sleight"
    | "squirm"
    | "grace"
    | "bear"
    | "steel"
    | "grit"
    | "draw"
    | "frame"
    | "form"
    | "read"
    | "reflex"
    | "sense"
    | "reason"
    | "recall"
    | "esoterica"
    | "aura"
    | "hope"
    | "sway"
    | "grasp"
    | "anchor"
    | "weave";

export const SKILL_LABELS: Record<SkillKey, string> = {
    force: "Force",
    brace: "Brace",
    feat: "Feat",
    sleight: "Sleight",
    squirm: "Squirm",
    grace: "Grace",
    bear: "Bear",
    steel: "Steel",
    grit: "Grit",
    draw: "Draw",
    frame: "Frame",
    form: "Form",
    read: "Read",
    reflex: "Reflex",
    sense: "Sense",
    reason: "Reason",
    recall: "Recall",
    esoterica: "Esoterica",
    aura: "Aura",
    hope: "Hope",
    sway: "Sway",
    grasp: "Grasp",
    anchor: "Anchor",
    weave: "Weave"
};
